regex lib exploration - needed for rtools build (for libmagic currently found)

diff --git a/.github/workflows/mingw-w64-tiledb/PKGBUILD b/.github/workflows/mingw-w64-tiledb/PKGBUILD
--- a/.github/workflows/mingw-w64-tiledb/PKGBUILD
+++ b/.github/workflows/mingw-w64-tiledb/PKGBUILD
@@ -39,6 +39,14 @@ build() {
     echo 'unable to find *regex*'
   fi
   
+  echo 'find *libtre*'
+  if [[ $(find / -name '*libtre*') ]] ; then
+    find / -name '*libtre*' || true
+    echo 'found *libtre*'
+  else
+    echo 'unable to find *libtre*'
+  fi
+  
   export MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX="
   ${MINGW_PREFIX}/bin/cmake.exe \
     --trace \
