hunting missing core files n+7

diff --git a/scripts/azure-linux_mac.yml b/scripts/azure-linux_mac.yml
--- a/scripts/azure-linux_mac.yml
+++ b/scripts/azure-linux_mac.yml
@@ -37,45 +37,45 @@ steps:
     ulimit -c               # should output 'unlimited' now
     
     #https://developer.apple.com/forums/thread/53023?answerId=158378022#158378022
-    sudo chmod 1775 /cores
+    #~ sudo chmod 1775 /cores
+    #~ sudo chown $(whoami) /cores
     
-    echo "bump 1 for azure pipelines status page 'An unexpected error has occurred within this region of the page'"
-    touch /cores/areyouhere.txt
-    echo "some garbage" >> /cores/areyouthere.txt
-    if [[ -f /cores/areyouthere.txt ]]; then
-      cat /cores/areyouthere.txt
-    else
-      echo "why no /cores/areyouthere.txt?"
-    fi
-    ls -l /cores
-    ls -l /
+    #~ echo "bump 1 for azure pipelines status page 'An unexpected error has occurred within this region of the page'"
+    #~ touch /cores/areyouhere.txt
+    #~ echo "some garbage" >> /cores/areyouthere.txt
+    #~ if [[ -f /cores/areyouthere.txt ]]; then
+      #~ cat /cores/areyouthere.txt
+    #~ else
+      #~ echo "why no /cores/areyouthere.txt?"
+    #~ fi
+    #~ ls -l /cores
+    #~ ls -l /
     
-    sudo chown $(whoami) /cores
-    ls -l /
+    #~ ls -l /
     
-    echo "more garbage" >> /cores/areyoutherenow.txt
-    if [[ -f /cores/areyoutherenow.txt ]]; then
-      cat /cores/areyoutherenow.txt
-    else
-      echo "still nothing, missing /cores/areyoutherenow.txt"
-    fi
+    #~ echo "more garbage" >> /cores/areyoutherenow.txt
+    #~ if [[ -f /cores/areyoutherenow.txt ]]; then
+      #~ cat /cores/areyoutherenow.txt
+    #~ else
+      #~ echo "still nothing, missing /cores/areyoutherenow.txt"
+    #~ fi
     
-    sleep 100 &
-    killall -SIGSEGV sleep
-    sleep 100 &
-    killall -SIGILL sleep
+    #~ sleep 100 &
+    #~ killall -SIGSEGV sleep
+    #~ sleep 100 &
+    #~ killall -SIGILL sleep
     
-    if [[ -f $(which python) ]]; then
-    #echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python3          # Azure sets "SYSTEM=build" for unknown reasonas, which breaks the OpenSSL configure script
-    #try for one
-    echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nimport time,threading\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nt1=threading.Thread(name='thd1', target=lambda: time.sleep(5))\nt1.start()\nt2=threading.Thread(name='thd2', target=lambda: time.sleep(5))\nt2.start()\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python
-    #try for two
-    echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nimport time,threading\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nt1=threading.Thread(name='thd1', target=lambda: time.sleep(5))\nt1.start()\nt2=threading.Thread(name='thd2', target=lambda: time.sleep(5))\nt2.start()\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python
-    exit 41 #try this, core dumps alone apparently not enuf to stop mac build on azure pipelines
-    else
-      echo "unable to find python3!"
-      exit 42
-    fi
+    #~ if [[ -f $(which python) ]]; then
+    #~ #echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python3          # Azure sets "SYSTEM=build" for unknown reasonas, which breaks the OpenSSL configure script
+    #~ #try for one
+    #~ echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nimport time,threading\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nt1=threading.Thread(name='thd1', target=lambda: time.sleep(5))\nt1.start()\nt2=threading.Thread(name='thd2', target=lambda: time.sleep(5))\nt2.start()\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python
+    #~ #try for two
+    #~ echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nimport time,threading\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nt1=threading.Thread(name='thd1', target=lambda: time.sleep(5))\nt1.start()\nt2=threading.Thread(name='thd2', target=lambda: time.sleep(5))\nt2.start()\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python
+    #~ exit 41 #try this, core dumps alone apparently not enuf to stop mac build on azure pipelines
+    #~ else
+      #~ echo "unable to find python3!"
+      #~ exit 42
+    #~ fi
     
     # Azure sets "SYSTEM=build" for unknown reasons, which breaks the OpenSSL configure script
     #   - openssl configure uses ENV{SYSTEM} if available:
@@ -184,6 +184,11 @@ steps:
     $BUILD_REPOSITORY_LOCALPATH/bootstrap $bootstrap_args
 
     make -j4
+    #vvvvvvvvvvvvvvvvv
+    #remove us
+    make -j4 -C tiledb tiledb_unit
+    ./tiledb/test/tiledb_unit -d yes --crash
+    #^^^^^^^^^^^^^^
     make examples -j4
     make -C tiledb install
 
