core dump file processing for ubuntu (GA) CI

diff --git a/.github/workflows/build-ubuntu20.04-backwards-compatibility.yml b/.github/workflows/build-ubuntu20.04-backwards-compatibility.yml
--- a/.github/workflows/build-ubuntu20.04-backwards-compatibility.yml
+++ b/.github/workflows/build-ubuntu20.04-backwards-compatibility.yml
@@ -1,16 +1,18 @@
 name: build-ubuntu-20.04-backwards-compatibility
 on:
   push:
-  pull_request:
+  #~ pull_request:
 env:
   CXX: g++
 
 jobs:
   build:
-    runs-on: ubuntu-20.04
+    runs-on: ${{matrix.os}}
     if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
     strategy:
       matrix:
+        os:
+          - ubuntu-20.04
         # Note: v2_1_0 arrays were never created so its currently skipped
         tiledb_version: ["v1_4_0", "v1_5_0", "v1_6_0", "v1_7_0", "v2_0_0", "v2_2_0", "v2_2_3", "v2_3_0", "v2_4_0"]
     timeout-minutes: 120
@@ -44,6 +46,9 @@ jobs:
           TILEDB_COMPATIBILITY_VERSION: ${{ matrix.tiledb_version }}
         id: test
         run: |
+          #TBD: remove this core dump hack for production
+          pwd; ls -la ./
+          echo -e "nl=\"\\\n\"\nprint('aborting...'+nl)\nimport resource as res\nimport time,threading\nprint(res.getrlimit(res.RLIMIT_CORE))\nprint(nl)\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nt1=threading.Thread(name='thd1', target=lambda: time.sleep(5))\nt1.start()\nt2=threading.Thread(name='thd2', target=lambda: time.sleep(5))\nt2.start()\nimport sys\nsys.stdout.flush()\nsys.stderr.flush()\nimport os \nos.abort()" | python3
 
           git clone https://github.com/TileDB-Inc/TileDB-Unit-Test-Arrays.git --branch 2.4.0 test/inputs/arrays/read_compatibility_test
 
@@ -64,6 +69,43 @@ jobs:
           # make check | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
           ./tiledb/test/tiledb_unit -d yes "[backwards-compat]"| awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
 
+
+      - name: 'dump  core stacks'
+        if: ${{ always() == true   && startsWith(matrix.os, 'ubuntu-') == true }} # only run this job if the build step failed
+        run: |
+          # following contains answers with various possibilities for locating core files on various systems
+          # https://stackoverflow.com/questions/2065912/core-dumped-but-core-file-is-not-in-the-current-directory
+          #a 'gdb' is present there, not a file, other gdbs but seem assoc'd with non-general usage
+          #if [[ -f /usr/share/gdb ]]; then
+          #  dbgr="/usr/share/gdb"
+          #  dbgropts=" -q --core \$f --batch -ex \"thread apply all bt\" -ex \"quit\""
+          #fi
+          # lldb ref'd here located by doing trial in runner with find / -name "*lldb*" and sifting through the results.
+          if [[ ! -f /usr/lib/llvm-11/bin/lldb ]]; then
+            #lldb -c $f --batch -o 'bt all' -o 'quit'
+            dbgr="/usr/lib/llvm-11/bin/lldb"
+            #dbgropts=" -core \$f --batch -o 'bt all' -o 'quit'"
+          else
+            echo "debugger not found in previously seen location!"
+            exit 1
+          fi
+          echo "dbgr $dbgr"
+          for f in $(find /var/lib/apport/coredump -name 'core.*');
+            do
+              echo "stack trace for $f"
+              #currently assumes $dbgr to be lldb
+              sudo $dbgr -core $f --batch  -o 'bt all' -o 'quit'
+            done;
+
+      - name: 'upload any core artifacts' # https://github.com/actions/upload-artifact#where-does-the-upload-go
+        if: ${{ always() == true && startsWith(matrix.os, 'ubuntu-') == true }} # only run this job if the build step failed
+        uses: actions/upload-artifact@v2
+        with:
+          retention-days: 10
+          name: "${{github.action}}.${{ github.job }}.${{ matrix.os }}.${{ github.run_number }}.${{github.run_id}}.${{github.run_attempt}}.${{jobs.build.name}}"
+          if-no-files-found: warn # 'ignore', 'warn' or 'error' are available, defaults to `warn` 
+          path: |
+            /var/lib/apport/coredump/ # ubuntu specific
 
       - name: 'Test status check'
         run: |
