adjustments to example run result checking, try to set TILEDB_CI_SUCCESS to 0 when errors occur (over-riding any previous 'success' setting from tiledb_unit, tiledb_regression)

diff --git a/.github/workflows/build-macOS11-GCS.yml b/.github/workflows/build-macOS11-GCS.yml
--- a/.github/workflows/build-macOS11-GCS.yml
+++ b/.github/workflows/build-macOS11-GCS.yml
@@ -89,7 +89,6 @@ jobs:
           bootstrap_args="${bootstrap_args} --enable-release-symbols";
           source $GITHUB_WORKSPACE/scripts/ci/build_libtiledb.sh
 
-          
           BaseDir="$(pwd)"
           TestAppDir="$(pwd)/tiledb/examples/c_api"
           TestAppDataDir="$(pwd)/tiledb/examples/c_api/test_app_data"
@@ -99,7 +98,13 @@ jobs:
             rm -rf ${TestAppDataDir}
             mkdir ${TestAppDataDir}
             cd ${TestAppDataDir}
-            echo $exampleexe; $exampleexe; 
+            echo $exampleexe
+            $exampleexe; 
+            status=$?
+            if (($status != 0)) then
+              echo "ERROR: $exampleexe exited with $status"
+              echo "::set-output name=TILEDB_CI_SUCCESS::0"
+            fi
           done
           cd ${TestAppDir}
           rm -rf ${TestAppDataDir}
@@ -113,7 +118,13 @@ jobs:
             rm -rf ${TestAppDataDir}
             mkdir ${TestAppDataDir}
             cd ${TestAppDataDir}
-            echo $exampleexe; $exampleexe; 
+            echo $exampleexe 
+            $exampleexe; 
+            status=$?
+            if (($status != 0)) then
+              echo "ERROR: $exampleexe exited with $status"
+              echo "::set-output name=TILEDB_CI_SUCCESS::0"
+            fi
           done
           cd ${TestAppDir}
           rm -rf ${TestAppDataDir}
diff --git a/.github/workflows/build-ubuntu20.04-GCS.yml b/.github/workflows/build-ubuntu20.04-GCS.yml
--- a/.github/workflows/build-ubuntu20.04-GCS.yml
+++ b/.github/workflows/build-ubuntu20.04-GCS.yml
@@ -109,7 +109,7 @@ jobs:
           # make check | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
           ./tiledb/test/tiledb_unit -d yes | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
           ./tiledb/test/regression/tiledb_regression -d yes | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
-          
+
           BaseDir="$(pwd)"
           TestAppDir="$(pwd)/tiledb/examples/c_api"
           TestAppDataDir="$(pwd)/tiledb/examples/c_api/test_app_data"
@@ -119,7 +119,13 @@ jobs:
             rm -rf ${TestAppDataDir}
             mkdir ${TestAppDataDir}
             cd ${TestAppDataDir}
-            echo $exampleexe; $exampleexe; 
+            echo $exampleexe
+            $exampleexe; 
+            status=$?
+            if (($status != 0)) then
+              echo "ERROR: $exampleexe exited with $status"
+              echo "::set-output name=TILEDB_CI_SUCCESS::0"
+            fi
           done
           cd ${TestAppDir}
           rm -rf ${TestAppDataDir}
@@ -133,7 +139,13 @@ jobs:
             rm -rf ${TestAppDataDir}
             mkdir ${TestAppDataDir}
             cd ${TestAppDataDir}
-            echo $exampleexe; $exampleexe; 
+            echo $exampleexe 
+            $exampleexe; 
+            status=$?
+            if (($status != 0)) then
+              echo "ERROR: $exampleexe exited with $status"
+              echo "::set-output name=TILEDB_CI_SUCCESS::0"
+            fi
           done
           cd ${TestAppDir}
           rm -rf ${TestAppDataDir}
diff --git a/.github/workflows/build-ubuntu20.04-SERIALIZATION.yml b/.github/workflows/build-ubuntu20.04-SERIALIZATION.yml
--- a/.github/workflows/build-ubuntu20.04-SERIALIZATION.yml
+++ b/.github/workflows/build-ubuntu20.04-SERIALIZATION.yml
@@ -112,7 +112,13 @@ jobs:
             rm -rf ${TestAppDataDir}
             mkdir ${TestAppDataDir}
             cd ${TestAppDataDir}
-            echo $exampleexe; $exampleexe; 
+            echo $exampleexe
+            $exampleexe; 
+            status=$?
+            if (($status != 0)) then
+              echo "ERROR: $exampleexe exited with $status"
+              echo "::set-output name=TILEDB_CI_SUCCESS::0"
+            fi
           done
           cd ${TestAppDir}
           rm -rf ${TestAppDataDir}
@@ -126,7 +132,13 @@ jobs:
             rm -rf ${TestAppDataDir}
             mkdir ${TestAppDataDir}
             cd ${TestAppDataDir}
-            echo $exampleexe; $exampleexe; 
+            echo $exampleexe 
+            $exampleexe; 
+            status=$?
+            if (($status != 0)) then
+              echo "ERROR: $exampleexe exited with $status"
+              echo "::set-output name=TILEDB_CI_SUCCESS::0"
+            fi
           done
           cd ${TestAppDir}
           rm -rf ${TestAppDataDir}
