manylinux port attempt for GA CI

diff --git a/.github/workflows/build-ubuntu20.04-AZURE.yml b/.github/workflows/build-ubuntu20.04-AZURE.yml
--- a/.github/workflows/build-ubuntu20.04-AZURE.yml
+++ b/.github/workflows/build-ubuntu20.04-AZURE.yml
@@ -24,7 +24,7 @@ jobs:
       matrix:
         os:
           - ubuntu-20.04
-    if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
+    if: false # ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
     timeout-minutes: 90
     name: Build - ${{matrix.os}} - AZURE
     env:
@@ -112,6 +112,10 @@ jobs:
           # Bypass Catch2 Framework stdout interception with awk on test output
           # make check | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
           ./tiledb/test/tiledb_unit -d yes --crash | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
+          # ...core dump occurred, but apparently the awk masked the failure...
+          # hmm, could that mask happen in actual production crash??? Probably, hmm...
+          # duh, this file still had dumps for 'macos...'
+          #./tiledb/test/tiledb_unit -d yes --crash
 
           # Kill the running Azurite server
           kill -n 9 $AZURITE_PID
@@ -143,33 +147,41 @@ jobs:
           ulimit -c               # should output 'unlimited' now
           #echo -e "import resource as res\nprint(res.getrlimit(res.RLIMIT_CORE))\nres.setrlimit(res.RLIMIT_CORE,(res.RLIM_INFINITY,res.RLIM_INFINITY))\nprint(res.getrlimit(res.RLIMIT_CORE))\nimport os \nos.abort()" | python3
 
-      - name: 'Save cores dump stacks if any'
-        if: ${{ failure() == true && startsWith(matrix.os, 'macos-') == true }} # only run this job if the build step failed
+      - name: 'dump  core stacks'
+        if: ${{ always() == true   && startsWith(matrix.os, 'ubuntu-') == true }} # only run this job if the build step failed
         run: |
-          nfiles=$(ls /cores | wc -l)
-          if [[ $nfiles -eq 0 ]]; then
-            echo "no core files found"
-            exit 0
+          # following contains answers with various possibilities for locating core files on various systems
+          # https://stackoverflow.com/questions/2065912/core-dumped-but-core-file-is-not-in-the-current-directory
+          #a 'gdb' is present there, not a file, other gdbs but seem assoc'd with non-general usage
+          #if [[ -f /usr/share/gdb ]]; then
+          #  dbgr="/usr/share/gdb"
+          #  dbgropts=" -q --core \$f --batch -ex \"thread apply all bt\" -ex \"quit\""
+          #fi
+          # lldb ref'd here located by doing trial in runner with find / -name "*lldb*" and sifting through the results.
+          if [[ -f /usr/lib/llvm-11/bin/lldb ]]; then
+            #lldb -c $f --batch -o 'bt all' -o 'quit'
+            dbgr="/usr/lib/llvm-11/bin/lldb"
+            #dbgropts=" -core \$f --batch -o 'bt all' -o 'quit'"
+          else
+            echo "debugger not found in previously seen location!"
+            exit 1
           fi
-          cd $TILEDB_HOME
-          ls -la /cores
-          for f in $(find /cores -name 'core.*');
+          echo "dbgr $dbgr"
+          for f in $(find /var/lib/apport/coredump -name 'core.*');
             do
               echo "stack trace for $f"
-              lldb -c $f --batch -o 'bt all' -o 'quit'
+              #currently assumes $dbgr to be lldb
+              sudo $dbgr -core $f --batch  -o 'bt all' -o 'quit'
             done;
-
       - name: 'upload any core artifacts' # https://github.com/actions/upload-artifact#where-does-the-upload-go
-        if: ${{ failure() == true && startsWith(matrix.os, 'macos-') == true }} # only run this job if the build step failed
-        id: 'macos-coredumps'
+        if: ${{ always() == true && startsWith(matrix.os, 'ubuntu-') == true }} # only run this job if the build step failed
         uses: actions/upload-artifact@v2
         with:
           retention-days: 10
-          name: "coredumps.${{ github.job }}.${{ matrix.os }}.${{ github.run_number }}.${{github.run_id}}.${{github.run_attempt}}.${{github.action}}"
-          if-no-files-found: warn # 'ignore/', 'warn' or 'error' are available, defaults to `warn` 
+          name: "coredumps.${{ github.job }}.${{ matrix.os }}.${{ github.run_number }}.${{github.run_id}}.${{github.run_attempt}}"
+          if-no-files-found: warn # 'ignore', 'warn' or 'error' are available, defaults to `warn`
           path: |
-            ${{ github.workspace }}/tdbcores/
-            /cores/
+            /var/lib/apport/coredump/
 
       - name: 'Test status check'
         run: |
@@ -203,9 +215,225 @@ jobs:
           - os: 'macos-10.15'
             image: 'quay.io/pypa/manylinux2010_x86_64:2021-11-07-28723f3'
     container: ${{ matrix.os.image }} # TBD: Is this/that right location for image?
+    env:
+      TILEDB_SERIALIZATION: ON
+      CXX: g++
+      CC: gcc
+      CXXFLAGS: "-lrt"
+      CFLAGS: "-lrt"
+      USE_MANYLINUX: ON
+    #?container: ${{ matrix.os.include.image }} # TBD: Is this/that right location for image?
     #services:
     #  manylinux:
     #    image: ${{ matrix.os.image }} # TBD: Is this/that right location for image?
     steps:
       - name: 'something to fill til real work coded'
         run: echo running in container? # to be replaced with something more substantial (azure-linux_mac.yml GA quiv?)
+
+      # 'porting' of 'actions' from azure-linux_mac.yml
+      - name: 'Print env'
+        run: |
+        echo "'uname -s' is:"
+        echo "uname: " $(uname)
+        echo "uname -m: " $(uname -m)
+        echo "uname -r:" $(uname -r)
+        echo "uname -s: " $(uname -s)
+        echo "uname -v: " $(uname -v)
+        printenv
+
+      - name: 'usepythonversion@0'
+        if: ${{ env.TILEDB_ARROW_TESTS == "ON" }}
+        #uses: ?
+
+      - name: 'pythonitems'
+        if: ${{ env.TILEDB_ARROW_TESTS == "ON" }}
+        run: |
+          set -e pipefail
+          python -m pip install --upgrade pip virtualenv
+          if [[ "$TILEDB_ARROW_TESTS" == "ON" ]]; then
+            pip install pyarrow pybind11 numpy
+          fi
+
+      # maybe not needed for manylinux effort, but in azure-linux_mac.yml
+      - name: 'Install system headers (OSX 10.14 only)'
+        run: |
+          set -e pipefail
+          open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
+          sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -allowUntrusted -target /
+        shell: bash
+        if: ${{ runner.os == 'macOS' && env.imageName == 'macOS-10.14' }}
+
+      - name: 'Build and test libtiledb'
+        run: |
+          # enable core dumps
+          ulimit -c               # should output 0 if disabled
+          ulimit -c unlimited     # Enable core dumps to be captured (must be in same run block)
+          ulimit -c               # should output 'unlimited' now
+          # Azure sets "SYSTEM=build" for unknown reasons, which breaks the OpenSSL configure script
+          #   - openssl configure uses ENV{SYSTEM} if available:
+          #     https://github.com/openssl/openssl/blob/6d745d740d37d680ff696486218b650512bbbbc6/config#L56
+          #   - error description:
+          #     https://developercommunity.visualstudio.com/content/problem/602584/openssl-build-error-when-using-pipelines.htm
+          unset SYSTEM
+
+          # azure bash does not treat intermediate failure as error
+          # https://github.com/Microsoft/azure-pipelines-yaml/issues/135
+          set -xe pipefail
+
+          git config --global user.name 'Azure Pipeline'
+          git config --global user.email 'no-reply@tiledb.io'
+
+          if [[ "$BACKWARDS_COMPATIBILITY_ARRAYS" == "ON" ]]; then
+            git clone https://github.com/TileDB-Inc/TileDB-Unit-Test-Arrays.git --branch 2.3.0 test/inputs/arrays/read_compatibility_test
+          fi
+          #   displayName: 'Clone Unit-Test-Arrays'
+
+          # - bash: |
+          # Start HDFS server if enabled
+          if [[ "$TILEDB_HDFS" == "ON" ]]; then
+            # - ssh to localhost is required for HDFS launch...
+            # - /home/vsts has permissions g+w and is owned by user 'docker'
+            #   for VSTS purposes, so disable ssh strictness
+            sudo sed -i "s/StrictModes\ yes/StrictModes\ no/g" /etc/ssh/sshd_config
+
+            source scripts/install-hadoop.sh
+            source scripts/run-hadoop.sh
+          fi
+
+          # Start minio server if S3 is enabled
+          if [[ "$TILEDB_S3" == "ON" ]]; then
+            source scripts/install-minio.sh;
+            source scripts/run-minio.sh;
+          fi
+
+          # Start Azurite if Azure is enabled
+          if [[ "$TILEDB_AZURE" == "ON" ]]; then
+            source scripts/install-azurite.sh;
+            source scripts/run-azurite.sh;
+          fi
+
+          # Start GCS Emulator if GCS is enabled
+          if [[ "$TILEDB_GCS" == "ON" ]]; then
+            source scripts/install-gcs-emu.sh;
+            source scripts/run-gcs-emu.sh;
+          fi
+
+          # Set up arguments for bootstrap.sh
+          bootstrap_args="--enable=verbose";
+
+          # Enable TILEDB_STATIC by default
+          [ "$TILEDB_STATIC" ] || TILEDB_STATIC=ON
+          if [[ "$TILEDB_STATIC" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-static-tiledb";
+          fi
+          if [[ "$TILEDB_HDFS" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-hdfs";
+          fi;
+          if [[ "$TILEDB_S3" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-s3";
+          fi;
+          if [[ "$TILEDB_AZURE" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-azure";
+          fi;
+          if [[ "$TILEDB_GCS" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-gcs";
+          fi;
+          if [[ "$TILEDB_TOOLS" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-tools";
+          fi
+          if [[ "$TILEDB_DEBUG" == "ON" ]]; then
+            bootstrap_args="${bootstrap_args} --enable-debug";
+          fi
+          if [[ "$TILEDB_CI_ASAN" == "ON" ]]; then
+            # Add address sanitizer flag if necessary
+            bootstrap_args="${bootstrap_args} --enable-sanitizer=address --enable-debug";
+          fi
+          if [[ "$TILEDB_CI_TSAN" == "ON" ]]; then
+            # Add thread sanitizer flag if necessary
+            bootstrap_args="${bootstrap_args} --enable-sanitizer=thread --enable-debug";
+          fi
+          if [[ "$TILEDB_SERIALIZATION" == "ON" ]]; then
+            # Add serialization flag if necessary
+            bootstrap_args="${bootstrap_args} --enable-serialization";
+          fi
+          if [[ "$TILEDB_FORCE_BUILD_DEPS" == "ON" ]]; then
+            # Add superbuild flag
+            bootstrap_args="${bootstrap_args} --force-build-all-deps";
+          fi
+          if [[ "$AGENT_OS" == "Darwin" ]]; then
+            # We want to be able to print a stack trace when a core dump occurs
+            sudo chmod 1777 /cores
+            bootstrap_args="${bootstrap_args} --enable-debug";
+          fi
+
+          # displayName: 'Install dependencies'
+
+          mkdir -p $BUILD_REPOSITORY_LOCALPATH/build
+          cd $BUILD_REPOSITORY_LOCALPATH/build
+
+          # Configure and build TileDB
+          echo "Bootstrapping with '$bootstrap_args'"
+          $BUILD_REPOSITORY_LOCALPATH/bootstrap $bootstrap_args
+
+          make -j4
+          make examples -j4
+          make -C tiledb install
+
+          #- bash: |
+          cd $BUILD_REPOSITORY_LOCALPATH/build
+          ls -la
+
+          if [[ ( "$AGENT_OS" == "Linux" && "$TILEDB_S3" == "ON" ) ]]; then
+            # make sure docker is still running...
+            printenv
+            docker ps -a
+          fi
+
+          make -j4 -C tiledb tiledb_unit
+
+          if [[ "$TILEDB_CI_ASAN" == "ON" ]]; then
+            export ASAN_OPTIONS=detect_leaks=0 LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.5
+          fi
+
+          if [[ "$AGENT_OS" == "Darwin" && "$TILEDB_GCS" == "ON" ]]; then
+            # GCS unit tests are temporarily unsupported on CI for MACOS. Fake success with
+            # this echo.
+            echo "##vso[task.setvariable variable=TILEDB_CI_SUCCESS]1"
+          else
+            # run directly the executable, cmake catches the segfault and blocks
+            # the core dump
+            ./tiledb/test/tiledb_unit -d yes
+          fi
+
+          # Kill the running Minio server, OSX only because Linux runs it within
+          # docker.
+          if [[ ( "$AGENT_OS" == "Darwin" && "$TILEDB_S3" == "ON" ) ]]; then
+            kill -9 $MINIO_PID
+          fi
+
+          # Kill the running Azurite server
+          if [[ "$TILEDB_AZURE" == "ON" ]]; then
+            kill -9 $AZURITE_PID
+          fi
+
+          # Kill the running GCS emulator server Linux only because OSX does not
+          # run the emulator
+          if [[ "$AGENT_OS" != "Darwin" && "$TILEDB_GCS" == "ON" ]]; then
+            kill -9 $GCS_PID
+          fi
+
+          #  displayName: 'Build examples, PNG test, and benchmarks (build-only)'
+
+      - name: 'Test status check'
+        run: |
+          # tiledb_unit is configured to set a job-level variable TILEDB_CI_SUCCESS=1
+          # following the test run. If this variable is not set, the build should fail.
+          # see https://github.com/TileDB-Inc/TileDB/pull/1400 (5f0623f4d3)
+          if [[ "${{ steps.test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
+            exit 1;
+          fi
+
+      - name: "Print log files (failed build only)"
+        run: |
+          source $GITHUB_WORKSPACE/scripts/ci/print_logs.sh
+        if: ${{ failure() }} # only run this job if the build step failed
