Add vcpkg integration; update Google Cloud SDK version to 2.6.0 (#3920)
This PR adds [vcpkg](https://vcpkg.io/en/index.html) as a dependency for building TileDB with Google Cloud Storage enabled (`-DTILEDB_GCS=ON`).

- vcpkg is added as a submodule in `external/vcpkg`
- CMake integration is added to automatically:
    -  init the submodule, if not already initialized with `git submodule init --recursive`
    - set the vcpkg toolchain, if not already available
        - note that pre-installing vcpkg for system-wide use will provide binary caching utilization across multiple projects, whereas bootstrapping will only provide caching for builds against that source tree
- vcpkg.json is added to the root of the source tree (not sure if this can be moved to `external/`) with a `gcs` feature that can be conditionally enabled
    - this is automatically enabled in `cmake/init-submodule.cmake` conditional on `TILEDB_GCS`

Unrelated but necessary commits:
- fix zlib target usage in cmake to match upstream `FindZlib` target name `ZLIB::ZLIB` (vs current `Zlib::Zlib`)
- isolate the bootstrap and build steps in the `full-ci` matrix, in order to allow vcpkg to cache the dependency build outputs if the libtiledb build fails (this _may_ not be necessary)

---

Google Cloud Storage is updated to 2.6.0 (ExternalProject build is unchanged, and can be enabled with `-DTILEDB_GCS_CLASSIC=ON`)

---
TYPE: BUILD
DESC: Add vcpkg integration; update Google Cloud SDK version to 2.6.0

===

* Remove BUILD_MAGIC_MACOS_UNIVERSAL on azure

* Move CMake option definitions to BuildOptions.cmake

* Move AWS SDK path length check to FindAWSSDK

* Use PNG target to fix linkage in WebP unit test

* Separate build_libtiledb into bootstrap_ and build_

vcpkg builds all dependencies during the CMake configure step.
Splitting configure and build job steps will allow the vcpkg
configure+build step result to be cached even if something in
the subsequent libtiledb build step fails. Otherwise, the whole
none of the vcpkg build outputs will be reused (even if they
were successful in isolation, and unchanged in a subsequent run).

* Add vcpkg submodule at 2023.01.09

* Add automatic vcpkg submodule init step via CMake to ensure it exists

* Ensure checkout action clone full submodule recursively

* Teach tiledb to link directly against newer GCS SDK target name

* Teach tiledb to use upstream FindZlib with correct (uppercase) target name

* Build GCS SDK with vcpkg; update and pin to 2.6.0

- Disable google-cloud-cpp default-features to cut down build

* Install pkg-config via homebrew in unit-tests-runs

* Make vcpkg toolchain conditional on GCS enabled for now

* Add submodule fetch + full

* Only install vcpkg if VCPKG_ROOT isn't set

* Fix include path

* Set the toolchain file when using vcpkg submodule

---------

Co-authored-by: Paul J. Davis <paul.davis@tiledb.com>

diff --git a/.github/workflows/ci-linux_mac.yml b/.github/workflows/ci-linux_mac.yml
--- a/.github/workflows/ci-linux_mac.yml
+++ b/.github/workflows/ci-linux_mac.yml
@@ -55,6 +55,25 @@ jobs:
     name: ${{matrix.os}} - ${{ inputs.ci_backend }}${{ inputs.ci_option }}
     steps:
       - uses: actions/checkout@v3
+        with:
+            submodules: true
+            fetch-depth: 0
+
+      - name: Restore artifacts, or setup vcpkg for building artifacts
+        uses: lukka/run-vcpkg@v10
+        id: runvcpkg
+        with:
+          vcpkgJsonGlob: 'vcpkg.json'
+          vcpkgDirectory: '${{ github.workspace }}/external/vcpkg'
+
+      - name: List $GITHUB_WORKSPACE before build
+        run: find $GITHUB_WORKSPACE
+        shell: bash
+
+      - name: Prints output of run-vcpkg's action.
+        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
+      - name: Work around vcpkg default # https://github.com/microsoft/vcpkg/issues/143#issuecomment-705778244 ¯\_(ツ)_/¯
+        run:  find $GITHUB_WORKSPACE/external/vcpkg/triplets/* -type f -exec sh -c "echo \"\nset(VCPKG_BUILD_TYPE release)\n\" >> {}" \;
 
       - name: 'Ubuntu Prelim'
         if: ${{ startsWith(matrix.os, 'ubuntu-') == true }}
@@ -73,24 +92,44 @@ jobs:
           python -m pip install --upgrade pip virtualenv
           pip install pyarrow pybind11 numpy
 
-      - name: 'Build and test libtiledb'
-        id: test
+      - name: 'Brew setup on macOS' # x-ref c8e49ba8f8b9ce
+        if: ${{ startsWith(matrix.os, 'macos-') == true }}
+        run: |
+          set -e pipefail
+          brew install pkg-config
+
+      - name: 'Configure libtiledb build'
+        id: configure
         shell: bash
         run: |
           set -e pipefail
 
-          ## ** NOTE: most of these steps must run in the same shell context **
+          #####################################################
+          # We want to run bootstrap in an isolated step in order to
+          # cache vcpkg deps across runs if the libtiledb build fails.
 
+          source $GITHUB_WORKSPACE/scripts/ci/bootstrap_libtiledb.sh
+
+      - name: 'Build and test libtiledb'
+        id: build_and_test
+        shell: bash
+        run: |
+          set -e pipefail
 
           ###################################################
           # Start helper processes, such as backend emulator
-          # if applicable
+          # if applicable.
+
+          #  ** NOTE: most tests must run in the same shell **
+          #  **       as build-services, especially tests   **
+          #  **       requiring a backend emulator.         **
 
           source $GITHUB_WORKSPACE/scripts/ci/posix/build-services-start.sh
 
           #####################################################
-          # Build libtiledb using `bootstrap_args` as set above
+          # Build libtiledb using bootstrap set above
 
+          source $GITHUB_WORKSPACE/scripts/ci/bootstrap_libtiledb.sh
           source $GITHUB_WORKSPACE/scripts/ci/build_libtiledb.sh
 
           ###################################################
@@ -142,10 +181,10 @@ jobs:
 
       - name: 'Test status check'
         run: |
-          # tiledb_unit is configured to set a job-level variable TILEDB_CI_SUCCESS=1
+          # tiledb_unit is configured to set a  variable TILEDB_CI_SUCCESS=1
           # following the test run. If this variable is not set, the build should fail.
           # see https://github.com/TileDB-Inc/TileDB/pull/1400 (5f0623f4d3)
-          if [[ "${{ steps.test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
+          if [[ "${{ steps.build_and_test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
             exit 1;
           fi
 
