Add end-to-end tests for GCP.

diff --git a/.github/workflows/test-cloud-e2e.yml b/.github/workflows/test-cloud-e2e.yml
--- a/.github/workflows/test-cloud-e2e.yml
+++ b/.github/workflows/test-cloud-e2e.yml
@@ -7,6 +7,11 @@ on:
         required: true
         default: true
         type: boolean
+      run_gcp:
+        description: 'Run Google Cloud Platform tests'
+        required: true
+        default: true
+        type: boolean
   push:
     branches:
       - dev
@@ -81,6 +86,105 @@ jobs:
           # Allow forks to specify different values.
           AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT || 'tiledbci' }}
           TILEDB_VFS_E2E_TEST_FILE: ${{ vars.AZURE_E2E_TEST_FILE || 'azure://tiledb/test.txt' }}
+        run: |
+          set -e pipefail
+
+          #####################################################
+          # Jump to our build directory after starting object
+          # store mock servers
+
+          cd $GITHUB_WORKSPACE/build
+
+          ###################################################
+          # Run tests
+
+          # Bypass Catch2 Framework stdout interception with awk on test output
+          ./tiledb/test/tiledb_unit -d yes "[vfs][e2e]" | awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'
+
+      - name: 'Test status check'
+        run: |
+          # tiledb_unit is configured to set a  variable TILEDB_CI_SUCCESS=1
+          # following the test run. If this variable is not set, the build should fail.
+          # see https://github.com/TileDB-Inc/TileDB/pull/1400 (5f0623f4d3)
+          if [[ "${{ steps.test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
+            exit 1;
+          fi
+
+      - name: "Print log files (failed build only)"
+        run: |
+          source $GITHUB_WORKSPACE/scripts/ci/print_logs.sh
+        if: ${{ failure() }} # only run this job if the build step failed
+
+  gcp:
+    runs-on: ubuntu-latest
+    if: inputs.run_gcp != 'false'
+    environment: gcp-e2e-test
+    env:
+      bootstrap_args: --enable-gcs --enable-ccache
+    permissions:
+      id-token: write # Get OIDC token for authentication to Azure
+    name: Google Cloud Platform
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      # Configure required environment variables for vcpkg to use
+      # GitHub's Action Cache
+      - uses: actions/github-script@v6
+        with:
+          script: |
+            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
+            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
+
+      - name: Prevent vpckg from building debug variants
+        run: python ./scripts/ci/patch_vcpkg_triplets.py
+
+      - name: Setup sccache
+        uses: mozilla-actions/sccache-action@v0.0.3
+
+      - name: 'Configure libtiledb'
+        id: configure
+        shell: bash
+        run: |
+          set -e pipefail
+
+          # Show CMake Version
+          cmake --version
+
+          source $GITHUB_WORKSPACE/scripts/ci/bootstrap_libtiledb.sh
+
+      - name: 'Build libtiledb'
+        id: build
+        shell: bash
+        run: |
+          set -e pipefail
+
+          #####################################################
+          # Build libtiledb using previous bootstrap
+
+          source $GITHUB_WORKSPACE/scripts/ci/build_libtiledb.sh
+
+      - id: auth
+        name: 'Authenticate to GCP'
+        uses: google-github-actions/auth@v1
+        with:
+            create_credentials_file: true
+            # Allow forks to specify different values.
+            workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER || 'projects/166903876158/locations/global/workloadIdentityPools/tiledb-ci/providers/github-actions' }}
+            service_account: ${{ vars.GCP_SERVICE_ACCOUNT || 'tiledb-core-ci@tiledb-gcp-testing.iam.gserviceaccount.com' }}
+
+      - name: Set workload identity configuration string
+        shell: bash
+        run: |
+          echo "TILEDB_VFS_GCS_WORKLOAD_IDENTITY_CONFIGURATION=$(cat ${{ steps.auth.outputs.credentials_file_path }})" >> $GITHUB_ENV
+
+      - name: 'Test libtiledb'
+        id: test
+        shell: bash
+        env:
+          TILEDB_VFS_E2E_TEST_FILE: ${{ vars.GCP_E2E_TEST_FILE || 'gcs://tiledb-ci/tiledb/test.txt' }}
+          TILEDB_VFS_GCS_IMPERSONATE_SERVICE_ACCOUNT: ${{ vars.GCP_IMPERSONATE_SERVICE_ACCOUNT || 'tiledb-core-ci-impersonated@tiledb-gcp-testing.iam.gserviceaccount.com' }}
         run: |
           set -e pipefail
 
